-- OELM per-reflection screen AOI metrics
-- Run this once in the Supabase SQL Editor before deploying the matching app.

begin;

create table if not exists public.pause_reflection_aoi (
  id bigint generated by default as identity primary key,
  session_id text not null,
  participant_id text,
  cohort_id text,
  pause_and_reflect_number integer not null check (pause_and_reflect_number > 0),
  paused_at timestamptz not null,
  resumed_at timestamptz not null,
  total_pause_ms bigint not null check (total_pause_ms >= 0),
  inside_aoi_ms bigint not null check (inside_aoi_ms >= 0 and inside_aoi_ms <= total_pause_ms),
  aoi_percent numeric(5,2) not null check (aoi_percent >= 0 and aoi_percent <= 100),
  valid_gaze_frames integer not null default 0 check (valid_gaze_frames >= 0),
  total_gaze_frames integer not null default 0 check (total_gaze_frames >= 0),
  ended_by text not null default 'resumed' check (ended_by in ('resumed', 'stopped')),
  created_at timestamptz not null default now(),
  unique (session_id, pause_and_reflect_number)
);

create index if not exists pause_reflection_aoi_cohort_participant_idx
  on public.pause_reflection_aoi (cohort_id, participant_id);

create index if not exists pause_reflection_aoi_session_idx
  on public.pause_reflection_aoi (session_id, pause_and_reflect_number);

alter table public.pause_reflection_aoi enable row level security;

grant select, insert, update on public.pause_reflection_aoi to anon, authenticated;
grant usage, select on sequence public.pause_reflection_aoi_id_seq to anon, authenticated;

drop policy if exists pause_reflection_aoi_read on public.pause_reflection_aoi;
create policy pause_reflection_aoi_read
  on public.pause_reflection_aoi
  for select
  to anon, authenticated
  using (true);

drop policy if exists pause_reflection_aoi_insert on public.pause_reflection_aoi;
create policy pause_reflection_aoi_insert
  on public.pause_reflection_aoi
  for insert
  to anon, authenticated
  with check (
    session_id <> ''
    and pause_and_reflect_number > 0
    and inside_aoi_ms <= total_pause_ms
  );

drop policy if exists pause_reflection_aoi_update on public.pause_reflection_aoi;
create policy pause_reflection_aoi_update
  on public.pause_reflection_aoi
  for update
  to anon, authenticated
  using (true)
  with check (
    session_id <> ''
    and pause_and_reflect_number > 0
    and inside_aoi_ms <= total_pause_ms
  );

commit;

